# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11pFYgtC-adMlA9Xx295fJYmSjmzwN3PU
"""

num1 = int(input("Digite um numero: "))
num2 = int(input("Digite um numero: "))

soma = num1 + num2
div = num1 / num2
mult = num1 * num2
sub = num1 - num2

status = 'sim'

while(status == 'sim'):
  operacao = input("Digite a operacao desejada: ")
  if (operacao == 'soma'):
    print(soma)
  elif (operacao == 'div'):
    print(div)
  elif (operacao == 'mult'):
    print(mult)
  elif (operacao == 'sub'):
    print(sub)

  status = input("Deseja prosseguir? Por favor digite sim ou nao: ")